Add logging
terraref/brapi pull request #12
Opened 2019-03-13 20:28 UTC by tcnichol

This pull request adds a logger (plus several log statements) in brapi. 

Not sure if it is correct, feedback needed.

2019-03-14 02:29 UTC, dlebauer commented
This seems to have the same changes as #10 along with the new logging ... perhaps it would make more sense to have the issue-537/cultivar-treatment-siteclear branch be the base for the pr instead of off master?

2019-03-14 13:31 UTC, robkooper requested changes

2019-03-14 13:31 UTC, robkooper commented on bety_brapi/controllers_impl/StudiesController_impl.py
> +    # print(query)
use logger.debug when you want to print the query. When we run in production we will run with loglevel INFO.

2019-03-21 15:37 UTC, robkooper commented
@tcnichol merging this request, but you are making changes to the logging branch that should be happening on the original branch. Please make changes from now on the issue-537/cultivar-treatment-siteclear branch

2019-03-21 15:38 UTC, robkooper commented
Actually can't merge due to conflict, can you fix conflict and then just merge.

2019-03-21 15:38 UTC, robkooper approved these changes

2019-05-01 13:10 UTC, robkooper commented
@tcnichol this seems to have more than just logging, what was else was done and why?

2019-05-01 13:10 UTC, robkooper commented
Working on a large rewrite of code, not sure what this does and how it needs to be incorperated in rewrite.

2019-05-01 16:17 UTC, tcnichol commented
Rob.

Some of the other stuff was that this was built off the other brapi pull request adding the new endpoints.

This just changes how logging is done, using an actual logger instead of print statements. I think it would be best that I decline this pull request, and if the feature is still wanted I can create a new one against master that would be easier to merge.

2019-05-06 15:29 UTC, tcnichol commented
this was built off an earlier branch and many of the changes no longer make sense so i am closing this one without mergin.

2019-05-06 15:29 UTC, closed without merging